
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 2019-05-27 09:23:35 by Jelly
//     对此文件的更改可能会导致不正确的行为，并且如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using LJD.App.Model.DbModels;

namespace LJD.App.Repository.IRepository
{
  
         
        /// <summary>
        /// 
        /// </summary>        
        public partial interface IPostRepository : IBaseRepository<Post>
        {

        }
         
        /// <summary>
        /// 角色菜单权限按钮关联表
        /// </summary>        
        public partial interface IR_RolePermissionRepository : IBaseRepository<R_RolePermission>
        {

        }
         
        /// <summary>
        /// 用户和角色关联表
        /// </summary>        
        public partial interface IR_sysUserInfo_sysRoleRepository : IBaseRepository<R_sysUserInfo_sysRole>
        {

        }
         
        /// <summary>
        /// 用户菜单权限按钮关联表
        /// </summary>        
        public partial interface IR_UserPermissionsRepository : IBaseRepository<R_UserPermissions>
        {

        }
         
        /// <summary>
        /// 菜单按钮表
        /// </summary>        
        public partial interface ISysFunctionRepository : IBaseRepository<SysFunction>
        {

        }
         
        /// <summary>
        /// 菜单表
        /// </summary>        
        public partial interface ISysMenusRepository : IBaseRepository<SysMenus>
        {

        }
         
        /// <summary>
        /// 组织单位表(部门表)
        /// </summary>        
        public partial interface ISysOrganizationUnitRepository : IBaseRepository<SysOrganizationUnit>
        {

        }
         
        /// <summary>
        /// 角色表
        /// </summary>        
        public partial interface ISysRoleRepository : IBaseRepository<SysRole>
        {

        }
         
        /// <summary>
        /// 用户表
        /// </summary>        
        public partial interface ISysUserInfoRepository : IBaseRepository<SysUserInfo>
        {

        }
         
        /// <summary>
        /// 流程分类表
        /// </summary>        
        public partial interface IWfInstanceTypeRepository : IBaseRepository<WfInstanceType>
        {

        }
         
}  