
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 2019-05-27 09:23:59 by Jelly
//     对此文件的更改可能会导致不正确的行为，并且如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using LJD.App.Model.DbModels;

namespace LJD.App.Service.IService
{     
         
         
        /// <summary>
        /// 
        /// </summary>        
        public partial interface IPostService : IBaseService<Post>
        {

        }
         
        /// <summary>
        /// 角色菜单权限按钮关联表
        /// </summary>        
        public partial interface IR_RolePermissionService : IBaseService<R_RolePermission>
        {

        }
         
        /// <summary>
        /// 用户和角色关联表
        /// </summary>        
        public partial interface IR_sysUserInfo_sysRoleService : IBaseService<R_sysUserInfo_sysRole>
        {

        }
         
        /// <summary>
        /// 用户菜单权限按钮关联表
        /// </summary>        
        public partial interface IR_UserPermissionsService : IBaseService<R_UserPermissions>
        {

        }
         
        /// <summary>
        /// 菜单按钮表
        /// </summary>        
        public partial interface ISysFunctionService : IBaseService<SysFunction>
        {

        }
         
        /// <summary>
        /// 菜单表
        /// </summary>        
        public partial interface ISysMenusService : IBaseService<SysMenus>
        {

        }
         
        /// <summary>
        /// 组织单位表(部门表)
        /// </summary>        
        public partial interface ISysOrganizationUnitService : IBaseService<SysOrganizationUnit>
        {

        }
         
        /// <summary>
        /// 角色表
        /// </summary>        
        public partial interface ISysRoleService : IBaseService<SysRole>
        {

        }
         
        /// <summary>
        /// 用户表
        /// </summary>        
        public partial interface ISysUserInfoService : IBaseService<SysUserInfo>
        {

        }
         
        /// <summary>
        /// 流程分类表
        /// </summary>        
        public partial interface IWfInstanceTypeService : IBaseService<WfInstanceType>
        {

        }
         
}
 