
 

//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//     生成时间 2019-05-27 09:24:04 by Jelly
//     对此文件的更改可能会导致不正确的行为，并且如果重新生成代码，这些更改将会丢失。
//     
// </auto-generated>
//------------------------------------------------------------------------------
using LJD.App.Model.DbModels;
using LJD.App.Repository.IRepository;
using LJD.App.Service.IService;
using LJD.App.Repository.IUnitOfWork;

namespace LJD.App.Service.Service
{     
         
         
        /// <summary>
        /// 
        /// </summary>        
        public partial class PostService : BaseService<Post>, IPostService
        {
            private readonly IPostRepository _postRepository;
            private readonly IUnitOfWork _unitOfWork;

            public  PostService(IPostRepository iPostRepository,IUnitOfWork unitOfWork) : base(iPostRepository)
            {
                _postRepository = iPostRepository;
                _unitOfWork = unitOfWork;
            } 

        } 
         
        /// <summary>
        /// 角色菜单权限按钮关联表
        /// </summary>        
        public partial class R_RolePermissionService : BaseService<R_RolePermission>, IR_RolePermissionService
        {
            private readonly IR_RolePermissionRepository _r_RolePermissionRepository;
            private readonly IUnitOfWork _unitOfWork;

            public  R_RolePermissionService(IR_RolePermissionRepository iR_RolePermissionRepository,IUnitOfWork unitOfWork) : base(iR_RolePermissionRepository)
            {
                _r_RolePermissionRepository = iR_RolePermissionRepository;
                _unitOfWork = unitOfWork;
            } 

        } 
         
        /// <summary>
        /// 用户和角色关联表
        /// </summary>        
        public partial class R_sysUserInfo_sysRoleService : BaseService<R_sysUserInfo_sysRole>, IR_sysUserInfo_sysRoleService
        {
            private readonly IR_sysUserInfo_sysRoleRepository _r_sysUserInfo_sysRoleRepository;
            private readonly IUnitOfWork _unitOfWork;

            public  R_sysUserInfo_sysRoleService(IR_sysUserInfo_sysRoleRepository iR_sysUserInfo_sysRoleRepository,IUnitOfWork unitOfWork) : base(iR_sysUserInfo_sysRoleRepository)
            {
                _r_sysUserInfo_sysRoleRepository = iR_sysUserInfo_sysRoleRepository;
                _unitOfWork = unitOfWork;
            } 

        } 
         
        /// <summary>
        /// 用户菜单权限按钮关联表
        /// </summary>        
        public partial class R_UserPermissionsService : BaseService<R_UserPermissions>, IR_UserPermissionsService
        {
            private readonly IR_UserPermissionsRepository _r_UserPermissionsRepository;
            private readonly IUnitOfWork _unitOfWork;

            public  R_UserPermissionsService(IR_UserPermissionsRepository iR_UserPermissionsRepository,IUnitOfWork unitOfWork) : base(iR_UserPermissionsRepository)
            {
                _r_UserPermissionsRepository = iR_UserPermissionsRepository;
                _unitOfWork = unitOfWork;
            } 

        } 
         
        /// <summary>
        /// 菜单按钮表
        /// </summary>        
        public partial class SysFunctionService : BaseService<SysFunction>, ISysFunctionService
        {
            private readonly ISysFunctionRepository _sysFunctionRepository;
            private readonly IUnitOfWork _unitOfWork;

            public  SysFunctionService(ISysFunctionRepository iSysFunctionRepository,IUnitOfWork unitOfWork) : base(iSysFunctionRepository)
            {
                _sysFunctionRepository = iSysFunctionRepository;
                _unitOfWork = unitOfWork;
            } 

        } 
         
        /// <summary>
        /// 菜单表
        /// </summary>        
        public partial class SysMenusService : BaseService<SysMenus>, ISysMenusService
        {
            private readonly ISysMenusRepository _sysMenusRepository;
            private readonly IUnitOfWork _unitOfWork;

            public  SysMenusService(ISysMenusRepository iSysMenusRepository,IUnitOfWork unitOfWork) : base(iSysMenusRepository)
            {
                _sysMenusRepository = iSysMenusRepository;
                _unitOfWork = unitOfWork;
            } 

        } 
         
        /// <summary>
        /// 组织单位表(部门表)
        /// </summary>        
        public partial class SysOrganizationUnitService : BaseService<SysOrganizationUnit>, ISysOrganizationUnitService
        {
            private readonly ISysOrganizationUnitRepository _sysOrganizationUnitRepository;
            private readonly IUnitOfWork _unitOfWork;

            public  SysOrganizationUnitService(ISysOrganizationUnitRepository iSysOrganizationUnitRepository,IUnitOfWork unitOfWork) : base(iSysOrganizationUnitRepository)
            {
                _sysOrganizationUnitRepository = iSysOrganizationUnitRepository;
                _unitOfWork = unitOfWork;
            } 

        } 
         
        /// <summary>
        /// 角色表
        /// </summary>        
        public partial class SysRoleService : BaseService<SysRole>, ISysRoleService
        {
            private readonly ISysRoleRepository _sysRoleRepository;
            private readonly IUnitOfWork _unitOfWork;

            public  SysRoleService(ISysRoleRepository iSysRoleRepository,IUnitOfWork unitOfWork) : base(iSysRoleRepository)
            {
                _sysRoleRepository = iSysRoleRepository;
                _unitOfWork = unitOfWork;
            } 

        } 
         
        /// <summary>
        /// 用户表
        /// </summary>        
        public partial class SysUserInfoService : BaseService<SysUserInfo>, ISysUserInfoService
        {
            private readonly ISysUserInfoRepository _sysUserInfoRepository;
            private readonly IUnitOfWork _unitOfWork;

            public  SysUserInfoService(ISysUserInfoRepository iSysUserInfoRepository,IUnitOfWork unitOfWork) : base(iSysUserInfoRepository)
            {
                _sysUserInfoRepository = iSysUserInfoRepository;
                _unitOfWork = unitOfWork;
            } 

        } 
         
        /// <summary>
        /// 流程分类表
        /// </summary>        
        public partial class WfInstanceTypeService : BaseService<WfInstanceType>, IWfInstanceTypeService
        {
            private readonly IWfInstanceTypeRepository _wfInstanceTypeRepository;
            private readonly IUnitOfWork _unitOfWork;

            public  WfInstanceTypeService(IWfInstanceTypeRepository iWfInstanceTypeRepository,IUnitOfWork unitOfWork) : base(iWfInstanceTypeRepository)
            {
                _wfInstanceTypeRepository = iWfInstanceTypeRepository;
                _unitOfWork = unitOfWork;
            } 

        } 
         
}
