// <auto-generated />
using System;
using Ly.Admin.Data.EF.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Ly.Admin.Data.EF.Migrations
{
    [DbContext(typeof(LyAdminDbContext))]
    partial class LyAdminDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Ly.Admin.Model.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id")
                        .HasComment("主键Id");

                    b.Property<string>("Author")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("1")
                        .HasColumnName("author")
                        .HasComment("作者");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("body")
                        .HasComment("内容");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("created_by")
                        .HasComment("创建人");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_time")
                        .HasComment("创建时间");

                    b.Property<int>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValue(1)
                        .HasColumnName("delete_flag")
                        .HasComment("删除标识");

                    b.Property<int>("SortId")
                        .HasColumnType("int(11)")
                        .HasColumnName("sort_id")
                        .HasComment("排序");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title")
                        .HasComment("标题");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("update_by")
                        .HasComment("更新人");

                    b.Property<DateTime?>("UpdatedTime")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("update_time")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.ToTable("tb_post");
                });

            modelBuilder.Entity("Ly.Admin.Model.SysAuth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id")
                        .HasComment("主键Id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("created_by")
                        .HasComment("创建人");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_time")
                        .HasComment("创建时间");

                    b.Property<int>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValue(1)
                        .HasColumnName("delete_flag")
                        .HasComment("删除标识");

                    b.Property<string>("LoginIP")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("login_IP")
                        .HasComment("最后登录IP");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime")
                        .HasColumnName("login_time")
                        .HasComment("最后登录时间戳");

                    b.Property<int>("Platform")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValue(-1)
                        .HasColumnName("platform")
                        .HasComment("登录平台");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("refresh_token")
                        .HasComment("刷新令牌");

                    b.Property<DateTime>("RefreshTokenExpiredTime")
                        .HasColumnType("datetime")
                        .HasColumnName("refresh_token_expired_time")
                        .HasComment("刷新令牌过期时间");

                    b.Property<int>("SortId")
                        .HasColumnType("int(11)")
                        .HasColumnName("sort_id")
                        .HasComment("排序");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("update_by")
                        .HasComment("更新人");

                    b.Property<DateTime?>("UpdatedTime")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("update_time")
                        .HasComment("更新时间");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.ToTable("sys_auth");

                    b
                        .HasComment("认证信息");
                });

            modelBuilder.Entity("Ly.Admin.Model.SysMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id")
                        .HasComment("主键Id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("created_by")
                        .HasComment("创建人");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_time")
                        .HasComment("创建时间");

                    b.Property<int>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValue(1)
                        .HasColumnName("delete_flag")
                        .HasComment("删除标识");

                    b.Property<int>("Hierarchy")
                        .HasColumnType("int(1)")
                        .HasColumnName("hierarchy")
                        .HasComment("层级");

                    b.Property<int>("IsDisplay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValue(1)
                        .HasColumnName("is_display")
                        .HasComment("是否显示");

                    b.Property<string>("MenuIcon")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("menu_icon")
                        .HasComment("图标");

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("menu_name")
                        .HasComment("菜单名称");

                    b.Property<int>("MenuType")
                        .HasColumnType("int(1)")
                        .HasColumnName("menu_type")
                        .HasComment("菜单类型");

                    b.Property<string>("MenuUrl")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("menu_url")
                        .HasComment("菜单链接");

                    b.Property<int>("OpenType")
                        .HasColumnType("int(1)")
                        .HasColumnName("open_type")
                        .HasComment("打开方式");

                    b.Property<int>("ParentId")
                        .HasColumnType("int(11)")
                        .HasColumnName("parent_id")
                        .HasComment("父级");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("permission_code")
                        .HasComment("权限码");

                    b.Property<int>("SortId")
                        .HasColumnType("int(11)")
                        .HasColumnName("sort_id")
                        .HasComment("排序");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValue(1)
                        .HasColumnName("status")
                        .HasComment("状态");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("update_by")
                        .HasComment("更新人");

                    b.Property<DateTime?>("UpdatedTime")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("update_time")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.ToTable("sys_menu");

                    b
                        .HasComment("菜单表");
                });

            modelBuilder.Entity("Ly.Admin.Model.SysRRoleMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id")
                        .HasComment("主键Id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("created_by")
                        .HasComment("创建人");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time")
                        .HasComment("创建时间");

                    b.Property<int>("DeleteFlag")
                        .HasColumnType("int(1)")
                        .HasColumnName("delete_flag")
                        .HasComment("删除标识");

                    b.Property<int>("MenuId")
                        .HasColumnType("int(11)")
                        .HasColumnName("menu_id")
                        .HasComment("菜单Id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("role_id")
                        .HasComment("角色Id");

                    b.Property<int>("SortId")
                        .HasColumnType("int(11)")
                        .HasColumnName("sort_id")
                        .HasComment("排序");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("update_by")
                        .HasComment("更新人");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_time")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.ToTable("sys_r_role_menu");

                    b
                        .HasComment("角色菜单对应关系");
                });

            modelBuilder.Entity("Ly.Admin.Model.SysRUserMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id")
                        .HasComment("主键Id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("created_by")
                        .HasComment("创建人");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time")
                        .HasComment("创建时间");

                    b.Property<int>("DeleteFlag")
                        .HasColumnType("int(1)")
                        .HasColumnName("delete_flag")
                        .HasComment("删除标识");

                    b.Property<int>("HavePermission")
                        .HasColumnType("int(1)")
                        .HasColumnName("have_permission")
                        .HasComment("是否拥有权限");

                    b.Property<int>("MenuId")
                        .HasColumnType("int(11)")
                        .HasColumnName("menu_id")
                        .HasComment("菜单Id");

                    b.Property<int>("SortId")
                        .HasColumnType("int(11)")
                        .HasColumnName("sort_id")
                        .HasComment("排序");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("update_by")
                        .HasComment("更新人");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_time")
                        .HasComment("更新时间");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id")
                        .HasComment("用户Id");

                    b.HasKey("Id");

                    b.ToTable("sys_r_user_menu");

                    b
                        .HasComment("用户菜单对应关系");
                });

            modelBuilder.Entity("Ly.Admin.Model.SysRUserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id")
                        .HasComment("主键Id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("created_by")
                        .HasComment("创建人");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_time")
                        .HasComment("创建时间");

                    b.Property<int>("DeleteFlag")
                        .HasColumnType("int(1)")
                        .HasColumnName("delete_flag")
                        .HasComment("删除标识");

                    b.Property<int>("RoleId")
                        .HasColumnType("int(11)")
                        .HasColumnName("role_id")
                        .HasComment("角色Id");

                    b.Property<int>("SortId")
                        .HasColumnType("int(11)")
                        .HasColumnName("sort_id")
                        .HasComment("排序");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("update_by")
                        .HasComment("更新人");

                    b.Property<DateTime?>("UpdatedTime")
                        .HasColumnType("datetime")
                        .HasColumnName("update_time")
                        .HasComment("更新时间");

                    b.Property<int>("UserId")
                        .HasColumnType("int(11)")
                        .HasColumnName("user_id")
                        .HasComment("用户Id");

                    b.HasKey("Id");

                    b.ToTable("sys_r_user_role");

                    b
                        .HasComment("用户角色对应关系");
                });

            modelBuilder.Entity("Ly.Admin.Model.SysRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id")
                        .HasComment("主键Id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("created_by")
                        .HasComment("创建人");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_time")
                        .HasComment("创建时间");

                    b.Property<int>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValue(1)
                        .HasColumnName("delete_flag")
                        .HasComment("删除标识");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("remark")
                        .HasComment("备注");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("role_name")
                        .HasComment("角色名称");

                    b.Property<int>("SortId")
                        .HasColumnType("int(11)")
                        .HasColumnName("sort_id")
                        .HasComment("排序");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValue(1)
                        .HasColumnName("status")
                        .HasComment("状态");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("update_by")
                        .HasComment("更新人");

                    b.Property<DateTime?>("UpdatedTime")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("update_time")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.ToTable("sys_role");

                    b
                        .HasComment("角色表");
                });

            modelBuilder.Entity("Ly.Admin.Model.SysUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(11)")
                        .HasColumnName("id")
                        .HasComment("主键Id");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("created_by")
                        .HasComment("创建人");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("created_time")
                        .HasComment("创建时间");

                    b.Property<int>("DeleteFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValue(1)
                        .HasColumnName("delete_flag")
                        .HasComment("删除标识");

                    b.Property<int>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValue(0)
                        .HasColumnName("gender")
                        .HasComment("性别");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("password")
                        .HasComment("密码");

                    b.Property<string>("RealName")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("real_name")
                        .HasComment("姓名");

                    b.Property<int>("SortId")
                        .HasColumnType("int(11)")
                        .HasColumnName("sort_id")
                        .HasComment("排序");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(1)")
                        .HasDefaultValue(1)
                        .HasColumnName("status")
                        .HasComment("状态");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int(11)")
                        .HasColumnName("update_by")
                        .HasComment("更新人");

                    b.Property<DateTime?>("UpdatedTime")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime")
                        .HasColumnName("update_time")
                        .HasComment("更新时间");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("user_name")
                        .HasComment("用户名");

                    b.HasKey("Id");

                    b.ToTable("sys_user");

                    b
                        .HasComment("用户表");
                });
#pragma warning restore 612, 618
        }
    }
}
